### ISSUE TITLE
Errors due to quotes (syntax error, unexpected tIDENTIFIER, expecting '}')

### ISSUE THREAD

**Issue by jed** [less/less.ruby#10]
LESS is currently choking on rules that contain quotation marks, such as this line from Eric Meyer's CSS Reset:

blockquote:before, blockquote:after, q:before, q:after { content: ""; }

**Comment by robbyrussell** [comment]
Jed,

I just added a spec to test this and it appears that it's only hanging up on the first '{'. If you add a new line after that, does it work?

**Comment by jed** [comment]
Yep, that does the trick!

**Comment by cloudhead** [comment]
I'll look into this, thanks.

**Comment by cloudhead** [comment]
Just pushed 0.8.10 to rubyforge, this should work now.

**Comment by jed** [comment]
Great, thanks!
