### ISSUE TITLE
mixins are overwriting rules that come next

### ISSUE THREAD

**Issue by daz-codes** [less/less.ruby#100]
`.red{color:red;background:red;}`

`#foo{.red;color:green;}`

The order that I put this in isn't being respected by LESS and it is outputting:

`#foo{color:green;color:red;background:red;}`

This is awkward as I like to overwrite some mixin properties. In fact I'd go as far to say that any specific properties should always trump a mixin's property regardless of order.

DAZ

**Comment by daz-codes** [comment]
This is version 1.2.10 btw

**Comment by cloudhead** [comment]
oh yea, this was me being a little lazy : ) — should be an easy fix.

**Comment by daz-codes** [comment]
On second thoughts I think it should be the source order that determines precedence - ie any declarations, mixins or not, will overwrite an y previous declarations. This way it copies how CSS currently works

**Comment by daz-codes** [comment]
I'm actually struggling to replicate this - it seems to be fairly random which order is used. This makes it difficult to consistently overwrite mixin properties.

**Comment by cloudhead** [comment]
Fixed in 1.2.13 — it only affected dynamic mixins.
