### ISSUE TITLE
Dynamic Mixins can't access global variables

### ISSUE THREAD

**Issue by daz-codes** [less/less.ruby#101]
```
@a:20;

.foo(@bar:1)
{
width:10px * @bar * @a;
}

#test{.foo(3);}
```

This throws an error:
! Variable Name Error: @a in \* is undefined.

I thought that ALL mixins and classes would have access to a variable defined in the global scope? This is useful for global settings.

Cheers,

DAZ

**Comment by cloudhead** [comment]
good find, just fixed this and pushed the new version to gemcutter.

I haven't tested it accross files though, but your example works now.

**Comment by xdissent** [comment]
Oh thank god. The last update killed Grid LESS completely. =)

**Comment by xdissent** [comment]
Question: can mixins alter the value of variables in the parent scope? It looks like maybe they can access but not change the values. I'll try some tests, just wondering if anyone knew off hand what the current behaviour is.

**Comment by xdissent** [comment]
Yeah it looks like setting a variable in a mixin creates a local variable instead of changing the global variable if one exists. I guess this makes sense, but you also cannot access global variables from within an imported file, making the notion of configurable external libraries impossible with the current version. So Grid LESS and every other thing I've done in LESS is broken again right now.

**Comment by cloudhead** [comment]
hmmm, could you give me an example? I just tested this out, and it works as expected:

globals.less

```
@var: 98px;
```

lib.less

```
@import "globals";
.mix (@a: 0) { width: @var; height: @a; }
```

main.less

```
@import "lib";
.test { .mix(2px); }
```

main.css

```
.test { width: 98px; height: 2px; }
```

**Comment by xdissent** [comment]
I was thinking about this all wrong. You're right. What I was trying to do is alter the value of a global variable for use in later mixins. I'm now using nested mixins instead. I was trying to do this:

```
@glob: red;

.mixin(@loc: green) {
    color: @glob;
    background-color: @loc;
    @glob: black;
}

.test(@arg: blue) {
    color: @glob;
    background-color: @arg;
}

body {
    .mixin(yellow);

    p {
        .test(brown);
    }
}
```

but now I'm using something like this:

```
@glob: red;

.mixin(@loc: green) {
    color: @glob;
    background-color: @loc;
    @glob: black;

    .test(@arg: blue) {
        color: @glob;
        background-color: @arg;
    }
}

body {
    .mixin;

    p {
        .test(brown);
    }
}
```

It works perfectly and the value of `@glob` is passed to the `.test` mixin. See the issue I just posted about the `.mixin` mixin not being able to take arguments.

**Comment by daz-codes** [comment]
If you slightly change the example, it breaks:

```
@glob: red;

.mixin(@loc: green) {
  color: @glob;
  background-color: @loc;
  @glob: black;

  .test(@arg: blue) {
      color: @glob;
    background-color: @arg;
  }
}

body {
  .mixin;

  p {
    .test;
  }
}
```

For some reason, you need to specify an argument when calling nested mixins (.test in this case) for them to work. Otherwise the error message is
    ! Mixin Name Error: .test is undefined.

**Comment by xdissent** [comment]
Yeah I created a new issue for the arguments problem the other day.

**Comment by daz-codes** [comment]
You beat me to it! I've added another case that doesn't work.
