### ISSUE TITLE
Mixins not evaluated unless followed by some other declaration or passed an argument.

### ISSUE THREAD

**Issue by xdissent** [less/less.ruby#102]
With this mixin:

```
.setup(@loc: #00f) {
    color: @loc;
}
```

and this declaration:

```
body {
    .setup;
}
```

or this declaration:

```
body {
    .setup();
}
```

no actual CSS is generated at all. However, with this declaration:

```
body {
    .setup(#f00);
}
```

or this one:

```
body {
    .setup;
    background-color: #0f0;
}
```

the mixin is evaluated correctly and CSS is generated. It looks like mixins without args are called slightly differently. I'm about to create another issue to demonstrate what is probably a related bug.

**Comment by cloudhead** [comment]
fixed in 1.2.13 — great find, also cleared up another bug. Feel free to reopen if there's still an issue.
