### ISSUE TITLE
less 1.1.13 apparently chokes on rules containing a comma

### ISSUE THREAD

**Issue by erisdev** [less/less.ruby#106]
I'm not sure whether multiple text-shadows is standard CSS, but Gecko and WebKit both agree that it's perfectly cromulent.

The complaint it spits my way is thus:
    on line 34: expected one of / ! ; } got , after:
    :link:hover    { text-shadow : #ffc300 0 0 4px

The whole line in question is thus:
    :link:hover    { text-shadow : #ffc300 0 0 4px, black 1px 1px 1px }

As you can see, it's winking at me in a rather creepily (and somewhat beakedly) _and_ it's failing to parse my stylesheet. For now, I suppose I'll move the two offending rules to a static CSS file, but it would be nice to have everything in one place.

**Comment by cloudhead** [comment]
Fixed in 1.2.11, grab it with `sudo gem install less -s http://gemcutter.org`

**Comment by erisdev** [comment]
Excellent, thanks! Somehow I managed to stay completely oblivious to the fact that 1.2 even existed. <del>Is this version safe for use in production code since it doesn't appear to be available in the default rubygems repositories?</del> Ah, it appears that comment used to call it the development version. Well, I'll give it a try!

**Comment by cloudhead** [comment]
yea, it's dev, but it's stable and tested. The only unstable part is the new dynamic mixin functionality.

**Comment by erisdev** [comment]
Alright, it's working perfectly now. Thanks again!
