### ISSUE TITLE
Seems like Growl message should trigger on successful update when watching.

### ISSUE THREAD

**Issue by timkelty** [less/less.ruby#107]
When your less files get bigger and you're 'watch'ing, it can take a little while for the .css file to be generated. I find myself with a terminal window open wait for the success message, which can annoying especially when you have a whole screen of 'successfully updated'.

I was expecting the Growl support to do just this, but apparently it only growls on an error. It would be great if it growled on successful update as well!

**Comment by cloudhead** [comment]
Oh : ). I can add a command line option to have it growl on success too. Maybe just a `--verbose` flag.

**Comment by timkelty** [comment]
Sounds perfect!

**Comment by cloudhead** [comment]
I merged a patch in for this a couple days ago. Works with the --verbose flag.

**Comment by timkelty** [comment]
Great, love it.
