### ISSUE TITLE
optimal @font-face syntax breaks

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#115]
the ideal cross-browser @font-face syntax of =>

@font-face {
    font-family: "FONT";
    src: url("/font/FONT.eot");
    src: local("FONT"),
        url("../font/FONT.woff") format("woff"),
        url("../font/FONT.otf") format("opentype"),
        url("../font/FONT.otf#FONT") format("svg");
}

breaks the compiling (due to the comma after the second src attribute, i'm assuming). is there a way allow for this or wrap a piece of css with syntax that tells the less compiler to ignore attempting to process it?

**Comment by cloudhead** [comment]
this works in the current development version, 1.2.12 — feel free to reopen an issue if you're still having issues!
