### ISSUE TITLE
Variables don't seem to work in IE alpha filter

### ISSUE THREAD

**Issue by michaek** [less/less.ruby#117]
Trying something like this (version 1.2.12):
filter: alpha(opacity=@ie_opacity);

Leads to the error:
! Syntax Error: on line 10: expected one of , ) ; } got @ after:

Thanks!

**Comment by cloudhead** [comment]
Fixed in 1.2.15

**Comment by michaek** [comment]
Thanks - no more syntax error. But the scope of variables seems to be wrong within the parentheses after "alpha".

Example: 
.opacity (@alpha:1) {
  @ie_opacity: @alpha*100;
  filter: alpha(opacity=@ie_opacity);
  -khtml-opacity: @alpha;
  -moz-opacity: @alpha;
  opacity: @alpha;
}

If I use a mixin like: .opacity(.6), here's the output:
  filter: alpha(opacity=1);
  -khtml-opacity: 0.6;
  -moz-opacity: 0.6;
  opacity: 0.6;

Seems like the IE version is using the default value, not the passed value.

**Comment by cloudhead** [comment]
ah yes, I did this really quickly and forgot about it being used in dynamic mixins. I'll look into it shortly

**Comment by michaek** [comment]
That's awesome - thanks!

**Comment by devgru** [comment]
Looks like my issue is kinda same: http://github.com/cloudhead/less/issues/#issue/127
