### ISSUE TITLE
Giving font-height and line-height in the same declaration does not work

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#12]
body {
font: 12px/16px Tahoma;
}

becomes

body { font: 0px Tahoma; }

**Comment by cloudhead** [comment]
Aha, yes it must be trying to do a division, will add that special case, thanks.

**Comment by cloudhead** [comment]
Disallowing operations on border and background property declarations for now. Referred to as 'compound'. It will now output an error message when you try to do this. For font, it will just skip the operation.
