### ISSUE TITLE
NoMethodError: undefined method `dissolve' for [@var, "-", 3.0]:Array

### ISSUE THREAD

**Issue by mcvsama** [less/less.ruby#122]
This exception rises when I try to use computations in less, for example:

Less.parse "@var: 3px; a { width: @var - 3; }"

Version that I'm using: 1.2.15. Ruby: 1.8.7.

**Comment by cloudhead** [comment]
sorry about that, should be working now, update your gem to 1.2.17

**Comment by mcvsama** [comment]
Works great now. Thank you soooo much. ;-)
