### ISSUE TITLE
Duplicate code when using comma 

### ISSUE THREAD

**Issue by casselda** [less/less.ruby#128]
The following example results in duplicate css code:
# navigation {

```
    .sf-menu, .sf-menu * {
            padding: 0;
            list-style: none;
            margin: 0
    }
```

}

this will result in:
# navigation .sf-menu \* {

```
    padding: 0;
    list-style: none;
    margin: 0;
```

}
# navigation .sf-menu \* {

```
    padding: 0;
    list-style: none;
    margin: 0;
```

}

AND NOT
# navigation .sf-menu,
# navigation .sf-menu \* {

```
    padding: 0;
    list-style: none;
    margin: 0;
```

}

**Comment by donut** [comment]
It only happens with a selector has tags and IDs or class in it.

#### Less input

```
a, b, c, body, h2 {
    color: white;
}

#hello, .pinky, .brain {
    color: pink;
}

#hello a, body.pinky, .brain h2 {
    color:  orange;
}
```

#### CSS output

```
a, b, c, body, h2 { color: white; }
#hello, .pinky, .brain { color: pink; }
#hello a { color: orange; }
body.pinky { color: orange; }
.brain h2 { color: orange; }
```

More discussion in the Google Group: [LessEfficient CSS output](http://groups.google.com/group/lesscss/browse_thread/thread/39b7fbff61360c01?hl=en)
