### ISSUE TITLE
If you have two rules, the last one is taken

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#13]
div {
width: 100px; // this rule is discarded
}

div {
color: red;
}

**Comment by cloudhead** [comment]
Good find, I can probably fix this with complex hash keys, which would also fix the ordering in ruby 1.8.

**Comment by cloudhead** [comment]
Moving this to 1.0, as I'm skipping 0.9

**Comment by ghost** [comment]
Nice. This is a biggie though :)

**Comment by cloudhead** [comment]
Yea, the new engine doesn't have a problem with this, and it should be coming out soon.
