### ISSUE TITLE
Explicit mixins / Mixin variables

### ISSUE THREAD

**Issue by timkelty** [less/less.ruby#138]
It would be nice if you could declare a mixin that wouldn't get rendered in the source, unless it was used as a mixin.

@mixin-name {
  color: black;
}
.some-class {
  @mixin-name;
}

...would just render
It would be nice if you could declare a mixin that wouldn't get rendered in the source, unless it was used as a mixin.

.some-class {
  color: black;
}

**Comment by cloudhead** [comment]
yea, this is possible with something like this:
    .mixin-name () { color: black; }   .some-class { .mixin-name; }
check the syntax in the readme.

**Comment by timkelty** [comment]
Yep, realize this now.

Thanks!
