### ISSUE TITLE
Nesting uses > instead of space

### ISSUE THREAD

**Issue by alexking** [less/less.ruby#150]
The [documentation](http://lesscss.org/docs.html) seems to suggest that this

```
#header {
    color: black;

    .navigation {
        font-size: 12px;
    }
    .logo {
        width: 300px;
        :hover { text-decoration: none }
    }
}
```

will result in this:

```
#header { color: black; }
#header .navigation {
  font-size: 12px;
}
#header .logo { 
  width: 300px; 
}
#header .logo:hover {
  text-decoration: none;
}
```

But when you run it through Less, you get 

```
#header { color: black; }
#header > .logo { width: 300px; }
#header > .logo > :hover { text-decoration: none; }
#header > .navigation { font-size: 12px; }
```

Which seems to actually be different. The way I understand it, using > selects the child, whereas using a space selects the descendant. So .logo has to be directly under #header for it to work, if .logo were inside another div inside of #header, nothing happens. 

Is there some way to use nesting and get #header .logo instead of #header > logo? I personally think if we have to have one or the other, automatically using the space instead of > would be much more useful. I don't generally care too much if the element is a direct child. Either way, it might be good to clarify the documentation some - I know it doesn't really say it'll generate that code, but it's kind of suggested.

**Comment by cloudhead** [comment]
Sounds like you have an old pre-1.0 release of LeSS, make sure you update, it should definitely not use `>`

**Comment by alexking** [comment]
Ah, thank you. I (thought I) updated the gem but I guess that wouldn't work if it was a pre release.
