### ISSUE TITLE
Pass arguments to mixins?

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#16]
Example:

@link_color: #050;
.link {
color: @link_color;
border-bottom: 1px dotted @link_color;
}
a {
.link;
outline: none; text-decoration: none;
}
a:hover {
@link_color: #0f0;
.link;
}
a:active {
@link_color: #000;
.link;
}

Perhaps it would still be useful to be able to explicitly parameterize mixins, just for the extra conciseness and clarity:

/\* hypothetical code */
a { .link(#080); }
a:hover { .link(#0f0); }
a:active { .link(#000); }

In the hypothetical example, you wouldn’t need to remember which exact variable to set before invoking the mixin .link.

**Comment by cloudhead** [comment]
This is definitely something I'm considering, although I might want to go for a more CSSy syntax, like:
    .link[@clr] {
        color: @clr;
    }
    #header { .link[#fff] }

**Comment by ghost** [comment]
Hmm... "[ ]" ? I think parens are CSS-like. For example here's how to do zebra striping on a table: tr:nth-child(odd). So I think parentheses "( )" would be fine for this.

**Comment by timothyjoh** [comment]
I wouldn't see a problem with a regular rubyish way of calling mixins like functions. Don't make the DSL too crazy CSS-like just to do advanced stuff.

**Comment by cloudhead** [comment]
Actually you're right, I forgot the use of parens in CSS, like url() etc. We could use [] for something else later on.

**Comment by pixel2** [comment]
It would be nice to be able to specify a default value on the argument as well (php syntax wise):

<pre>.link(@clr = #0f0) { color: @clr; border-bottom: 1px dotted @clr; }</pre>


And when used:

<pre>a { .link; }
a:active { .link(#000); }</pre>

**Comment by cloudhead** [comment]
yea for sure.

**Comment by xdissent** [comment]
This gets my vote for most important feature. It would open up amazing possibilities and provide a really elegant way of implementing things like Less based themes.

**Comment by leafo** [comment]
this is already possible due to the delayed evaluation

```
@arg: red;
.function { color: @arg; }

body { @arg: blue; .function; }
a { @arg: green; .function; }
p { .function; }
```

The results are what you expect

```
a { color: green; }
body { color: blue; }
p { color: red; }
```

**Comment by cloudhead** [comment]
1.2.\* is out now, closing.
