### ISSUE TITLE
filter !important

### ISSUE THREAD

**Issue by dougdroper** [less/less.ruby#162]
filter:alpha(opacity=80) !important; throws an error

**Comment by joeldrapper** [comment]
@dougdroper this doesn't throw an error for me. Are you sure your using the latest version?

**Comment by dougdroper** [comment]
@joeldrapper That's okay it was an old version.

**Comment by joeldrapper** [comment]
@dougdroper I was in the wrong repository and only just realised I forgot to check the dates. :P
