### ISSUE TITLE
Errors encountered when parsing *.less files

### ISSUE THREAD

**Issue by JonSidnell** [less/less.ruby#19]
I've just installed less, and thought I'd check everything was working before doing anything serious with it, and I'm getting errors.

The content of the styles.less file is:
# header

{
    color: black;
    .navigation 
    {
        font-size: 12px;
    }
    .logo 
    {
        width: 300px;
    }
}

and the errors output to the console are

!! errors were found in the .less file! 
{´╗┐"#header"=>{
     ^
line 1: syntax error, unexpected tASSOC, expecting $end
{´╗┐"#header"=>{
               ^
!! errors were found in the .less file! 
{´╗┐"#header"=>{
     ^
line 1: syntax error, unexpected tASSOC, expecting $end
{´╗┐"#header"=>{
               ^

I'm running Windows Server 2008 on 64-bit Intel if that helps.

**Comment by ghost** [comment]
Just ran the code through lessc (I'm using ruby 1.8.7 on OS X) and it came out fine without errors. What version of Ruby are you using? Would be annoying if this is system specific :/

**Comment by JonSidnell** [comment]
I was trying it with 1.9.1. My -v string was

ruby 1.9.1p0 (2009-01-30 1.9.1, revision 21907) [i386-mswin32]

I've just removed that and installed the Win32 version of 1.8.7, tried much simpler less code:

```
@brand_color: #4d926f;

#section {
background-color: @brand_color;
}
```

and this time got this output to the error console:

```
!! errors were found in the .less file! 
line 1: Invalid char `\357' in expression
line 1: Invalid char `\273' in expression
line 1: Invalid char `\277' in expression
!! errors were found in the .less file! 
line 1: Invalid char `\357' in expression
line 1: Invalid char `\273' in expression
line 1: Invalid char `\277' in expression
```

It's possible it's the version of Windows, or the 64-bit - both are reasonably non-standard. I'm away from my 32-bit, Vista-based laptop at the moment, but I'll try that when I can as it is _always_ possible I'm being a newbie numpty!

**Comment by cloudhead** [comment]
It seems like you have some non-ascii invisible characters in there, that would be causing an error.

**Comment by JonSidnell** [comment]
OK, I've located the source of the problem. The original file was created in Visual Studio, and it looks like Visual Studio prepends any text files it creates with a Byte-Order Mark to denote UTF-8 encoding. Creating a *.less file with another text editor yields success so it's not a system-based issue.

Is this something that is easily strippable before the file is parsed and processed? I understand that Visual Studio isn't a natural choice for working with Ruby-based code, but I can see real benefit to my ASP.NET based team, and I also know there's one or two Ruby and RoR IDEs that are built on top of VS so it may affect other Ruby developers as well.

**Comment by cloudhead** [comment]
I'll see what I can do. It seems kind of weird to me though, as not every language supports UTF-8...
