### ISSUE TITLE
SVG Data URI with Compression

### ISSUE THREAD

**Issue by joeyhoer** [less/less.ruby#203]
The test below illustrates an issue compiling SVG data URIs. When compressed (with YUI), the whitespace is collapsed within the markup, and that leads to breakage.

```
.test {
border-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0,0 24,26"><filter id="dropshadow" height="150%" width="150%"><feGaussianBlur in="SourceAlpha" stdDeviation="2"></feGaussianBlur><feOffset dx="0" dy="1" result="offsetblur"></feOffset><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter><polygon fill="hsl(0, 0%, 100%)" filter="url(#dropshadow)" points="12,3 2,13 12,23 22,13"></polygon></svg>') 30.76923% 29.16667% repeat;
border-width: 0 0 8px;
border-style: solid;
background-clip: padding-box;
margin-bottom: -8px;
    position: relative;
}
```

**Comment by mindfullsilence** [comment]
I don't think that's how svg data uri works. You're pasting in the xml code directly into your css. You need to base-64 encode the image. You can use this tool to do so:
[http://www.mobilefish.com/services/base64/base64.php]

See a good tutorial on SVG and css:
[http://css-tricks.com/using-svg/]

**Comment by lukeapage** [comment]
wrong repo - use

https://github.com/less/less.js/

also we switched to clean-css to avoid a couple of bugs.
