### ISSUE TITLE
Is it possible to place all css in one line?

### ISSUE THREAD

**Issue by alvassin** [less/less.ruby#205]
Hello, i'm using grunt and grunt-contrib-less for building lesscss and compressing js files with node.js.

I would like to place all css in one line - is that possible somehow with grunt? maybe it's possible to create some extra task for this?

Thanks in advance!

**Comment by mindfullsilence** [comment]
Are you talking about having the compiled output be on one line? Not sure less does it, but it wouldn't be too tough to set up an extra task after the file compiles to strip out carriage returns.

**Comment by alvassin** [comment]
Already found a solution for this, thanks!
