### ISSUE TITLE
border-radius's special syntax not supported?

### ISSUE THREAD

**Issue by Pym** [less/less.ruby#206]
```
border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%;
```

renders as:

```
border-radius: 50% 50% 50% 0.8333333333333334% 60% 40% 40%;
```

So, I tried to escape like this:

```
border-radius: ~"50% 50% 50% 50% / 60% 60% 40% 40%";
```

And now it gives me:

```
border-radius: 50% 50% 50%  60% 40% 40%;
```

Is it possible to make this code works?

**Comment by mindfullsilence** [comment]
Try dividing up the string interpolation and focusing on only the part that doesn't work:

```
    border-radius: 50% 50% 50% 50% ~"/" 50% 50% 50% 50%;
```

It's pretty ugly, but it does seem to compile as it should.

**Comment by lukeapage** [comment]
wrong repo - use

https://github.com/less/less.js/

also, fixed with strict maths. either use `~""50% / 60%` or turn on strictMaths
