### ISSUE TITLE
Feature request: !important variables impacting @imported variables

### ISSUE THREAD

**Issue by reggi** [less/less.ruby#207]
I just included [bootstrap](https://github.com/twitter/bootstrap) and [font awesome](https://github.com/FortAwesome/Font-Awesome) into a project I'm working on using [bower](https://github.com/twitter/bower). Bower downloaded both repo's into a `components` folder in my project.

My project looks like this

```
/components
    /bootstrap
    /Font-Awesome
/style.less
```

My `style.less`  file contains individual imports of all of `bootstraps` parts excluding `sprites.less` which shares classes with font awesome.

At the bottom of `style.less` I'm importing font awesome. Within that file at the top is a variable `@FontAwesomePath` which is a relative path to the `font` folder. This is invalid now that i've `@imported` the file.

I would like to not have to edit this variable within the repo, I wanna keep the rep clean and make all my changes in my files.

What I need would be the ability to override this variable from `style.less` like so.

```
@FontAwesomePath: "/components/Font-Awesome/font" !important;
@import "./components/Font-Awesome/less/font-awesome.less";
```

I think this makes loads of since, especially with projects like bower on the rise, less is going to need to pick up some of the slack.

**Comment by lukeapage** [comment]
wrong repo - use

https://github.com/less/less.js/
