### ISSUE TITLE
@import feature

### ISSUE THREAD

**Issue by cloudhead** [less/less.ruby#21]
Ability to import style-sheets as well as specific classes & namespaces.

**Comment by xdissent** [comment]
This functionality would make this tool an essential part of my daily life.

**Comment by xdissent** [comment]
I actually forked less and wrote a quick dirty hack that solves this. This project is really great, thanks.

**Comment by xdissent** [comment]
Since handling @import would be pretty similar to handling @media, should this issue be marked for inclusion in 0.9 as well? =)

**Comment by cloudhead** [comment]
This now works in the master branch. @media & @font-face too.
