### ISSUE TITLE
Creating own rules [sugar]

### ISSUE THREAD

**Issue by dangreen** [less/less.ruby#213]
What about this feature?
Example:

```
@rule box(@width, @height: @width) { // or ?box(@width, @height: @width)
    width: @width;
    height: @height;
}
// usage
.block { box: 10px } // width: 10px; height: 10px;
.search { box: 100px 10px } // width: 100px; height: 10px;
```

**Comment by lukeapage** [comment]
did you mean to add this bug here https://github.com/less/less.js/issues ?

also I think this is a duplicate I'm sure I've seen almost the same suggestion there.. probably from you?
