### ISSUE TITLE
Feature for debug mode?

### ISSUE THREAD

**Issue by Serabass** [less/less.ruby#214]
I just had an idea.
What if writing the name of the source LESS file and line number in the right selector (in debug mode, of course)?
Here is an example

div {
    p {
        a {
            color: white;
        }
    }
}

compiles to

:not([source="main.less:3:9"]) div p a { // this is a correct selector
    color: white;
}
or
:not([source="main.less"]):not([line="3"]):not([col="9"]) div p a { // this is a correct selector
    color: white;
}

That is, the first part will determine any element inside which there is an element of on the selector. A CSS3 ":not()" required to identify all the elements, as unlikely that there is an element with attribute "source", "line" and "col" equal to our line.

This will give us the opportunity to see the original position of the selector right in the console

Yes, maybe it slows down the rendering and generates a lot of garbage, but this is a debug mode.

**Comment by lukeapage** [comment]
did you mean to add this bug here https://github.com/less/less.js/issues ?

also debug line numbers essentially does this and sourcemaps in 1.5.0 go even further
