### ISSUE TITLE
@import will not behave like @import-once on symbolic links

### ISSUE THREAD

**Issue by tkrugg** [less/less.ruby#215]
Default `@import` behaviour in v1.4.2 is `@import-once`, which works as long as the absolute paths referencing a file are exactly same. 
Now if a `file.less` has a symbolic link `symfile.less`, and you import them both

```
@import "file.less";
@import "symfile.less";
```

less doesn't seem to see that it's the same file.

**Comment by lukeapage** [comment]
why would you have symbolic links and import both but not want one imported?

This is the wrong repo

use this one

https://github.com/less/less.js
