### ISSUE TITLE
unit() Broken for Percentages?

### ISSUE THREAD

**Issue by matthewwithanm** [less/less.ruby#217]
The docs don't explicitly mention using unit with "%", but I would assume that this should work:

```
@v: unit(100, %);
s { p: @v;}
```

However the output is:

``` css
s {
  p: %);
}
```

`unit(100, ~'%')` does work, however.

**Comment by lukeapage** [comment]
did you mean to add this bug here https://github.com/less/less.js/issues ?

**Comment by matthewwithanm** [comment]
Yeah, sorry. Too many windows open!
