### ISSUE TITLE
Imported variable interpolation

### ISSUE THREAD

**Issue by michelkaeser** [less/less.ruby#221]
Hi there

The following Gist gives: `NameError: variable @bootstrapDir is undefined in` https://gist.github.com/MaddinXx/6609523 while tests have shown that non-interpolated usage works well.

If you could take a look at that :)

**Comment by lukeapage** [comment]
Should this be in the less.js repo?

**Comment by michelkaeser** [comment]
Ah indeed. Going to reference it there. Thanks for the hint :)

**Comment by lukeapage** [comment]
We need to rename this repository
