### ISSUE TITLE
Syntax error with grouped CSS selectors and line breaks

### ISSUE THREAD

**Issue by attilagyorffy** [less/less.ruby#23]
_Description:_
The compiler fails when there is a line break between two or more grouped CSS selectors.

I usually tend to add line breaks between more grouped CSS selectors to avoid having really long lines in my files and it is also more readable.

_Example:_
This works just fine:

a#selector_a, a#selector_b {
  /\* rules defined here... */
}

However it fails whenever a line break is present between the selectors:

a#selector_a,
a#selector_b {
  /\* rules defined here... */
}

_Output:_
$ lessc modules.less modules.css 
!! errors were found in the .less file! 
line 127: syntax error, unexpected '\n', expecting tASSOC
line 128: syntax error, unexpected tASSOC, expecting $end
"a#selector_b"=>{

**Comment by cloudhead** [comment]
This should be fixed in the current version, you might have to update your gem!

**Comment by attilagyorffy** [comment]
Cool, now I've got v0.8.12 and it works just fine, I can clarify that. Thanks for your response.
