### ISSUE TITLE
Order of appearance in 1.8

### ISSUE THREAD

**Issue by augustl** [less/less.ruby#25]
Since the parser creates a regular ruby hash from the .less, the order of the declarations and rules aren't persisted. This:

```
h1, h2, h3, p{
    margin:0;
    padding:0;
    margin-bottom:.8em;
}
```

Turns into this:

```
h1, h2, h3, p { margin-bottom: 0.8em; margin: 0; padding: 0; }
```

Which leads to the margin-bottom being overridden by margin: 0;

Same goes for order of appearance of the declarations themselves, as mentioned. You might have rules that overrides other rules, based on order of appearance. Less may or may not break this, depending on the order the items gets in the Ruby hash.

**Comment by augustl** [comment]
Update: I'm working on fixing this ; )

**Comment by cloudhead** [comment]
Yea, this has been a problem for some people on ruby 1.8, and the reason why ruby 1.9 is recommended (hash order is preserved in 1.9) — The obvious solution would be to use an ordered hash implementation for 1.8, or an array of hashes, like:

```
[{'margin' => 0}, {'padding' => 0}]
```

But I'm open to any other solution : )

**Comment by slowernet** [comment]
As you may know, there are several extant ordered hash implementations for 1.8:

http://www.culann.com/2008/01/rails-goodies-activesupportorderedhash
http://loopkid.net/articles/2008/06/19/ordered-hashes-in-ruby-1-8

**Comment by rnmp** [comment]
Yeah! The same occurs with the selectors.
    body { }
    #home { }

Turns into:
    #home { }
    body { }

**Comment by xdissent** [comment]
This is a big blocker for me. Don't really want to upgrade Ruby, so are there any Ruby dudes out there with a quick fix for 1.8?

**Comment by augustl** [comment]
cloudhead is working on rewriting the parser with treetop, so this issue is being addressed. Nobody knows when it'll be finished, of course, but the progress is steady.

**Comment by cloudhead** [comment]
The rewrite is almost finished, and comes with some nifty new features!

**Comment by xdissent** [comment]
Sounds good. I added an opt install of ruby so I've managed to migrate some stuff in the meantime anyway. Great work fellas! Keep it coming and I'll try to do my part in this foreign Ruby territory.

**Comment by sgabello** [comment]
is the new engine available in the latest realease? Is it still affected by this bug?

**Comment by augustl** [comment]
This bug has been fixed.
