### ISSUE TITLE
IE hacks

### ISSUE THREAD

**Issue by zeppelin** [less/less.ruby#26]
Less doesn't swallow star and underscore hacks, the following fails to compile:

*padding: 0;
_padding: 1px;

**Comment by cloudhead** [comment]
Is that even valid CSS? never seen this before, but I'll look into it.

**Comment by zeppelin** [comment]
The star-hack is valid, as it's just an alphanumeric character. The underscore (as I can recall) is not, however I don't think this should be a deal-breaker. 

Since the star and the underscore hack is so widely accepted as good method working around IE-bugs, it would be a huge plus supporting them. (I wrote "huge plus" instead of "the very minimum". You decide which one I meant) ;)

A real-world example for the above:
If an element needs different line-height for IE7, its easier to adjust with a property, that modern browsers skip.

<pre>
.sg { 
    line-height: 1em;
    *line-height: 1.2em; /* for IE6&7 */
    _line-height: 1em; /* for IE6 */
}
</pre>


Without it, the following steps should be made:

<pre>
.sg { line-height: 1em; }
* html .sg { line-height: 1em; } /* for IE6 */
</pre>
- A separate CSS file for IE7 inside a conditional-comment.

I'm very aware that it's the valid way, but maintaining big -and I mean <strong>big</strong>\- sites like this is pretty time-consuming progress, not speaking about the possible errors when it happens that some changes and/or additons must be made on the site sometime later.

**Comment by cloudhead** [comment]
Alright, seems like a valid point, will fix this in the next patch.

**Comment by ghost** [comment]
I agree -- hacks are ugly but are part of web dev -- need to keep them working

**Comment by cloudhead** [comment]
Should work in 0.8.13, please close the issue to confirm!

**Comment by zeppelin** [comment]
Works fine, thank you for fixing it so quickly!

**Comment by cloudhead** [comment]
awesome, you're welcome.

**Comment by minimaldesign** [comment]
Hacks are pointless. Use conditional comments instead...
