### ISSUE TITLE
Selector ordering

### ISSUE THREAD

**Issue by zeppelin** [less/less.ruby#27]
Property order gets mixed in the output when nested into another selector. The following piece of code demonstrates the issue:

HTML:

<pre>
&lt;div class="section"&gt;&lt;/div&gt;
&lt;div class="wide section"&gt;&lt;/div&gt;
</pre>

(Less)CSS:

<pre>
.something {
.section { width: 100px; }
.wide { width: 200px; }
}
</pre>

The output is:

<pre>
.something .wide { width: 200px; }
.something .section { width: 100px; }
</pre>

Since the ordering in the CSS is for good reason, the compiler should retain it.

**Comment by cloudhead** [comment]
We're aware of this, issue #25 is where it's at — It's a ruby 1.8 problem, so if you have 1.9, you can use that, if not, you'll have to wait till we fix it.
