### ISSUE TITLE
NULL values

### ISSUE THREAD

**Issue by zeppelin** [less/less.ruby#28]
<strong>Feature request</strong>

To clean up property declarations a little, it would be useful to be able to use null values.
Whenever I need to overwrite some, but not all -for example margin- values, by default, it's a bit overcomplicated:

The ordinary method:

<pre>
.class { margin: 10px 10px 15px 20px; }
.another_class .class { margin-left: auto; margin-right: auto; }
</pre>

The suggested method:

<pre>
. class { margin: 10px 10px 15px 20px; }
.another_class .class { margin: null auto; }
</pre>

So null basically leaves the top and bottom margin intact, but the changes on the left/right will be compiled to:

<pre>
.another_class .class { margin-left: auto; margin-right: auto; }
</pre>

In my opinion, this makes the code much shorter (and therefore much readable), so I'd be glad to see something similar to this in a future release.

**Comment by cloudhead** [comment]
Interesting, I ran into this issue in the past, so I'm not opposed to having a way to deal with it. Maybe in a future release!
