### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by prtksxna** [less/less.ruby#30]
If the following CSS is written adding an additional definition throws a Ruby error.

<pre>div#some_id{
  div#some_other_id{
    color:red;
  }
  div#another_id{
    background: yellow;
  }
}</pre>

Instead of showing a wrong CSS or parsing error, the following Ruby error is thrown -
<pre>
/usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/tree.rb:53:in `each': hash modified during iteration (RuntimeError)
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/tree.rb:53:in `traverse'
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/engine.rb:32:in `compile'
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/engine.rb:130:in `to_css'
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/command.rb:57:in `compile'
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/../lib/less/command.rb:50:in `run!'
        from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.13/bin/lessc:72
        from /usr/local/bin/lessc:16:in `load'
        from /usr/local/bin/lessc:16
</pre>

**Comment by cloudhead** [comment]
Fixed in master which I will push to rubyforge soon.
