### ISSUE TITLE
Variable operations in variable declarations.

### ISSUE THREAD

**Issue by augustl** [less/less.ruby#32]
This will fail on 0.8.13. Dunno if it's still like this in HEAD, the gem is still 0.8.13 tho'.

```
@main_width: 750px;
@content_width: 600px;
@sidebar_width: @main_width - @content_width;
```

The calculations in @sidebar_width aren't performed.

**Comment by cloudhead** [comment]
that's weird, it's in the spec. the gem will be on rubyforge monday, for now you can use the github gem which is at 1.0.3. `sudo gem install cloudhead-less`
