### ISSUE TITLE
Syntax error if only statement within declaration doesn't end with a semicolon

### ISSUE THREAD

**Issue by mcmire** [less/less.ruby#33]
If I have this:

```
pre {
  white-space: pre
}
```

Less crashes with:

```
on line 35: expected one of { ; got `125` after:

pre {
  white-space: pre
```

If I put a semicolon after `white-space: pre` then Less is happy.

This is inconsistent with CSS, which allows a statement to not end in a semicolon if it's the only one in the declaration.

Same thing happens if the last statement within a declaration doesn't end in a semicolon.

**Comment by cloudhead** [comment]
semi-column at end of ruleset now works, as well as attribute selector, like h1[attr], Closed by fe9e55c54ab5e19b308d4fe56a2b1e7d3599e77c #34

**Comment by cloudhead** [comment]
thanks, fixed : ) - let me know if you still encounter this problem.

**Comment by mcmire** [comment]
Wow, that was fast! I'll try it out.
