### ISSUE TITLE
Incomplete support for attribute selectors

### ISSUE THREAD

**Issue by mcmire** [less/less.ruby#34]
It seems that this isn't supported yet:

```
abbr[title] { ... }
```

http://www.w3.org/TR/css3-selectors/#attribute-selectors

**Comment by cloudhead** [comment]
fixed, thanks! patch should be on rubyforge soon.

**Comment by pixel2** [comment]
Found another css3 selector that isn't working, not the end of the world though :)

<pre>p:not([class*="lead"]) { color: black; }</pre>

**Comment by cloudhead** [comment]
cool, just fixed it, will be online in a sec.
