### ISSUE TITLE
Properitary declarations

### ISSUE THREAD

**Issue by augustl** [less/less.ruby#35]
This will cause a parse error on 1.0.5

```
background: -webkit-gradient(linear, left top, left bottom, from(red), to(blue));
```

PS: Can't refer to hex colors (it'll turn into issue links), so I used 'red' and 'blue'. Both fails parsing, though.

**Comment by cloudhead** [comment]
Ok, will look into this, this'll get me going on the new functions feature.

**Comment by jeremyh** [comment]
Another example:

```
.dinosaurContainer {
    display: -moz-inline-stack;
}
```

**Comment by cloudhead** [comment]
`-moz-inline-stack` should work now, the more complex properties are still an issue.

**Comment by mechanicalchopsticks** [comment]
webkit has seconds as unit for the transitions.
    a {
        -webkit-transition: color 0.3s linear;
    }

This throws a syntax error:

```
Syntax Error: on line #: expected one of px em pc % pt cm mm / ; } got 115 after:

a {
        -webkit-transition: color .3
```

**Comment by cloudhead** [comment]
ahah cool, I'll add that to the units.

**Comment by augustl** [comment]
Perhaps it makes sense to add a last failover rule that can take anything? E.g. "unit / color / foo / bar / anything_but_semicolon", so that it'll parse but won't do anything magic with it. Handling every single properitary edge case sounds kind of over the top.

**Comment by cloudhead** [comment]
hmm yea that's an idea. Just parse it as an Anonymous node, if it doesn't parse as anything else.

**Comment by cloudhead** [comment]
Ok, so I added a catch-all rule, tested it with the -webkit-gradient construct, and it's working fine. v1.1.8

**Comment by jonbuda** [comment]
This still seems to be an issue with -webkit-transition. I have the line:

<pre>-webkit-transition: background-color .4s;</pre>


resulting in:

<pre>on line 86: expected one of [1;33mpx em pc % ex pt cm mm / ; }[0m got [1;33ms[0m after:</pre>
