### ISSUE TITLE
Inserting too many spaces

### ISSUE THREAD

**Issue by augustl** [less/less.ruby#36]
This less:

```
.box#newsletter
```

Will turn into this css:

```
.box #newsletter
```

That space shouldn't be there. That rule is a bit silly, I know, but it should still parse it without adding a space.

**Comment by cloudhead** [comment]
thanks, should be an easy fix.

**Comment by cloudhead** [comment]
fixed grammar for .class#id, Closed by 412d791a223732193f625e892352887e50261eea
