### ISSUE TITLE
color not correctly parsed

### ISSUE THREAD

**Issue by mildlyfunctional** [less/less.ruby#38]
When inserting a color like  #008584 the result file shows #8584

**Comment by mildlyfunctional** [comment]
I try this again:
When inserting a color like #zerozero8584 the result file shows #8584 (without the zero's) (just like github :) )

**Comment by jonbuda** [comment]
same thing happens to me.

**Comment by cloudhead** [comment]
Oh dear : ) - will fix this right now.

**Comment by cloudhead** [comment]
fixed issue with color padding: #9999 -> #009999, Closed by 1a80daf5c4717871b54706188eb65f96622bef7c
