### ISSUE TITLE
RGBA not working with transparent value

### ISSUE THREAD

**Issue by phongjalvn** [less/less.ruby#40]
I encoutered this problem when try to use rgba background color with transparent value:

.trans-black{
    background: rgba(0 , 0, 0, 0.5);
}

LESS convert it to hex value, but and wipe out transparent value like this:

.trans-black { background: #000000; }

**Comment by cloudhead** [comment]
This is being adressed, cwninja submitted a patch which takes care of this, and it'll find its way in the master sometime today or tomorrow.
