### ISSUE TITLE
Inefficient handling of comma separated selectors

### ISSUE THREAD

**Issue by jeremyh** [less/less.ruby#41]
The (commonly used) [meyer css reset](http://meyerweb.com/eric/tools/css/reset/)  is a rather extreme example of inefficient output:

The first selector is:
    html, body, div, span, applet, object, iframe,
    h1, h2, h3, h4, h5, h6, p, blockquote, pre,
    a, abbr, acronym, address, big, cite, code,
    del, dfn, em, font, img, ins, kbd, q, s, samp,
    small, strike, strong, sub, sup, tt, var,
    dl, dt, dd, ol, ul, li,
    fieldset, form, label, legend,
    table, caption, tbody, tfoot, thead, tr, th, td {
        margin: 0;
        padding: 0;
        border: 0;
        outline: 0;
        font-weight: inherit;
        font-style: inherit;
        font-size: 100%;
        font-family: inherit;
        vertical-align: baseline;
    }

Which is expanded out when compiled by less:

```
html {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
body {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
div {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
span {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
applet {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
object {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
iframe {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-weight: inherit;
  font-style: inherit;
  font-size: 100%;
  font-family: inherit;
  vertical-align: baseline;
}
```

etc..

The full output is 11k (the original Meyer reset is ~900 bytes).

**Comment by jeremyh** [comment]
While a full compressor isn't a high priority (as discussed in [issue 4](http://github.com/cloudhead/less/issues/#issue/4)), this kind of "low hanging fruit" seems worth addressing.

**Comment by jeremyh** [comment]
On further investigation, the size difference is negligible on a server with gzip enabled. 555 bytes for the Less compiled version, and 531 bytes for the original.

**Comment by cloudhead** [comment]
yea this has been somewhat of a concern, and I'm looking into the best way to fix it. Gzip will take care of it indeed, but can't you just use `* { ... }` in this case?

**Comment by jlindley** [comment]
Cloudhead, star-scrubbing like that can really screw with <input>, <select> and <textarea>, etc, which is why "html, html \* { }" style resets can cause trouble, this is more targeted.

**Comment by jlindley** [comment]
Oops - with input, select, and textarea tags, the html got stripped out in my previous comment.

**Comment by xdissent** [comment]
Oh, wow, it's another use case for metadata! We could define a "expand" property somehow, indicating that the rule shouldn't be parsed out into individual nodes.

**Comment by cloudhead** [comment]
Just pushed some changes which should take care of these, as long as they don't have nested rules in them. Looking into a better way to do this though.

**Comment by mechanicalchopsticks** [comment]
Now the gets:

```
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, bd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, head, tr, th, td {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-size: 100%;
  vertical-align: baseline;
  background: transparent;
}
body {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-size: 100%;
  vertical-align: baseline;
  background: transparent;
}
h2 {
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-size: 100%;
  vertical-align: baseline;
  background: transparent;
}
```

Not every selector in the list get duplicated though.

**Comment by cloudhead** [comment]
yea it's still far from perfect, but should definitely help.
