### ISSUE TITLE
error parsing attribute selectors without element name

### ISSUE THREAD

**Issue by jeremyh** [less/less.ruby#43]
eg.

```
[disabled] {
    color: #f00;
}
```

(Another low-priority defect from compiling my legacy codebase. Although some of these are easy to work around, I figure they are worth fixing to minimise friction for people converting css to Less).

**Comment by cloudhead** [comment]
fixed attribute selector without element name error, Closed by 3b6760835c4079facb23e16e7c3f5dfc763ca727
