### ISSUE TITLE
Incorrect colour value expansion

### ISSUE THREAD

**Issue by jeremyh** [less/less.ruby#44]
The colour value #f00 is incorrectly expanded to #f00f00 when compiled with less 1.0.6. 

 #f00 is equivalent to #ff0000.

**Comment by jeremyh** [comment]
See the [CSS colour spec](http://www.w3.org/TR/CSS2/syndata.html#value-def-color)

**Comment by cloudhead** [comment]
aha yea, you're right, it should be expanding the channels separately. should be an easy fix.

**Comment by cloudhead** [comment]
actually I just noticed this is fixed in cwninja's patch too. I'm pulling it in right now.
