### ISSUE TITLE
LESS cannot parse cyrillic character even in comments

### ISSUE THREAD

**Issue by devgru** [less/less.ruby#46]
subj.
LESS failed on reading /\* */-style comment, that contained some cyrillic characters.

**Comment by cloudhead** [comment]
I just tried this, and it seems to work fine..

```
.russian {
    content: "русский язык";
}
```

parses correctly on my machine.

**Comment by devgru** [comment]
Looks like it was my bug, because I've modified first line of bin/lessc to use ruby1.9 (I've decided to do this because I've installed gems 1.9), so I think this is because of unresolved dependencies.
Shame on me :-)

**Comment by cloudhead** [comment]
Ahah, well, good news I guess : )
