### ISSUE TITLE
Better evaluation engine

### ISSUE THREAD

**Issue by cloudhead** [less/less.ruby#5]
The evaluation engine is somewhat linear, which makes certain complex operations on namespaced variables problematic.
Reordering the operations may help, as well as separating the evaluations for variable definitions from css property declarations.
A better 'evaluate-on-demand' system could be implemented for a > 1.0 version.

**Comment by ghost** [comment]
Can we be more vague? :) Or do you mean the whole thing is so connected that most of it will need rewriting? So it's not a, fix A, B, C, and D, but, change the whole thing affair?

**Comment by cloudhead** [comment]
hehe don't worry about it, this is an implementation issue, not a usability one.

**Comment by cloudhead** [comment]
Rewrote it in Treetop, so moving this to 1.0
