### ISSUE TITLE
rgb broken

### ISSUE THREAD

**Issue by nirvdrum** [less/less.ruby#50]
It looks like the patch to treat color as a vector broke rgb colors.  The problem is that the array isn't flattened properly.  Thus, calling rgb(200, 200, 200), actually calls rgba([200, 200, 200], 1.0), creating an invalid number of arguments situation.

It appears none of the existing specs used rgb so it didn't get caught.

I fixed the issue with the following commit.  Please let me know if you have any questions.

30e2d8ebca3df18d6c835f953c06503778ba3cfe

**Comment by cloudhead** [comment]
Thanks!

**Comment by cloudhead** [comment]
fixed rgb issue, thanks to @nirvdrum, Closed by 823d14b53d9a29c1e6117850d3e7e051357ca66c

**Comment by nirvdrum** [comment]
Well, that was fast.  Thanks.
