### ISSUE TITLE
syntax error, unexpected tFLOAT, expecting tAMPER (SyntaxError)

### ISSUE THREAD

**Issue by minimaldesign** [less/less.ruby#51]
I just installed {less} and running `lessc test.less` I get this error... I can provide the whole error if that helps diagnose the problem... {less} looks totally awesome and I'm bummed I can't even get to try it :(

**Comment by cloudhead** [comment]
Do you have 1.1.7? I _just_ fixed this, it was caused by a recent update which wasn't compatible with ruby 1.8.

**Comment by minimaldesign** [comment]
nevermind... I reinstalled it and somehow it installed 1.1.6 before but this time it installed 1.1.7 and everything seems to be working fine! :)

**Comment by cloudhead** [comment]
great!
