### ISSUE TITLE
Doesn't parse !important

### ISSUE THREAD

**Issue by onlinesid** [less/less.ruby#55]
This line from blueprint 0.9 screen.css caused error:

input.span-1, textarea.span-1, input.span-2, textarea.span-2, input.span-3, textarea.span-3, input.span-4, textarea.span-4, input.span-5, textarea.span-5, input.span-6, textarea.span-6, input.span-7, textarea.span-7, input.span-8, textarea.span-8, input.span-9, textarea.span-9, input.span-10, textarea.span-10, input.span-11, textarea.span-11, input.span-12, textarea.span-12, input.span-13, textarea.span-13, input.span-14, textarea.span-14, input.span-15, textarea.span-15, input.span-16, textarea.span-16, input.span-17, textarea.span-17, input.span-18, textarea.span-18, input.span-19, textarea.span-19, input.span-20, textarea.span-20, input.span-21, textarea.span-21, input.span-22, textarea.span-22, input.span-23, textarea.span-23, input.span-24, textarea.span-24 {border-left-width:1px!important;border-right-width:1px!important;padding-left:5px!important;padding-right:5px!important;}

The error was:

! Syntax Error: on line 126: expected one of / ; } [ ( : \* . # - @media @font-face , { got ! after:

**Comment by cloudhead** [comment]
I'll look into this—in the meantime, adding a space before `!important` will fix it.

**Comment by cloudhead** [comment]
fixed `!important` not working when there is too much, or no whitespace. Closed by cc1f4cac68af38678114559ecf9d39e67cd65b95

**Comment by onlinesid** [comment]
Adding space before !important fixed it thanks
