### ISSUE TITLE
Newline before @import causing syntax error

### ISSUE THREAD

**Issue by unindented** [less/less.ruby#56]
If I have a file with this content (the \n added by me, it's just a blank line):
    \n
    @import "../common/reset";

The parser fails with this error:
    ! Syntax Error: on line 2: expected : got " after:

```
@import
```

If I delete that first blank line, and instead have this:
    @import "../common/reset";

Everything goes OK.

**Comment by cloudhead** [comment]
fixed @import not working if there is a new-line preceding, or from a string. Closed by e4a3f50fd395514d25080c1f409c6761c5e06ef5, #57
