### ISSUE TITLE
Less.parse "@import" error

### ISSUE THREAD

**Issue by unindented** [less/less.ruby#57]
From my irb I try to do:
    >> Less.parse "@import '../common/reset';"

And the parser spits back at me:
    TypeError: can't convert nil into String
            from (eval):454:in `join'
            from (eval):454:in`build'
            from (eval):16:in `build'
            from (eval):15:in`map'
            from (eval):15:in `build'
            from /Library/Ruby/Gems/1.8/gems/less-1.1.10/lib/less/engine.rb:36:in`parse'
            from /Library/Ruby/Gems/1.8/gems/less-1.1.10/lib/less/engine.rb:46:in `to_css'
            from /Library/Ruby/Gems/1.8/gems/less-1.1.10/lib/less.rb:31:in`parse'
            from (irb):16

If I use `lessc` on a file with that same content from the same location, it works.

**Comment by cloudhead** [comment]
ah, yea, because it's looking for the path of the file, but there is no file : ) — will fix it, thanks.

**Comment by cloudhead** [comment]
fixed in v1.1.11

**Comment by unindented** [comment]
Wow, thanks for the fast response. Keep up the great work on this awesome project!
