### ISSUE TITLE
cursor property with url value

### ISSUE THREAD

**Issue by macavon** [less/less.ruby#58]
If you want to use a custom image for the cursor property, using its URL as the value, you must provide a list of cursors, separated by commas, with one of the standard named cursors at the end, like this:

```
cursor: url('expand-cursor.gif'), crosshair;
```

(See http://www.w3.org/TR/CSS21/ui.html#cursor-props)

When I try this in a less file, the parser chokes on the comma. If you just put the URL on its own, the CSS does not validate and all the browsers I've tried it on ignore the invalid property value.

**Comment by macavon** [comment]
Turns out this is a special case of the more general problem identified in issue 63. See also 53.

**Comment by cloudhead** [comment]
Indeed! closing this, refer to #53.
