### ISSUE TITLE
MixedUnitsError is limiting

### ISSUE THREAD

**Issue by guns** [less/less.ruby#59]
Mixing units in compound declarations like:

```
.foo { margin 0 20px 1.5em 20px; }
```

result in a MixedUnitsError, raised here in Less -> Node -> Expression#evaluate:

```
unit = literals.map do |node|
  node.unit
end.compact.uniq.tap do |ary|
  raise MixedUnitsError, self * ' ' if ary.size > 1
end.join
```

This seems to be done for grammar purity and ease of operator implementation, but mixed units are legal and useful in compound statements. Furthermore, LESS should happily do arithmetic on whatever sequence of units, since it need only operate on the numbers and then reattach whatever units it started with.

I'm not familiar with the Tree Top library, so I'm not sure what it would take to change this. If there is no interest in providing this in the near future, I will go ahead and propose a patch when I get some time.

**Comment by cloudhead** [comment]
fixed shorthand properties with mixed units giving an error. Closed by c27a4180044205e7af2e27277c5eb0c2a3eab41c

**Comment by cloudhead** [comment]
This turned out really easy to fix : )

You still can't do `1em + 4px`, but: `margin: 2cm 4em (2px + 2px) 5` will work.

**Comment by guns** [comment]
Cool! 

I hadn't considered adding pixels and ems together actually. I was only thinking about multiplication :(

**Comment by cloudhead** [comment]
But what result would you expect in say `2px * 4em` ?

**Comment by guns** [comment]
Well, I assumed that you would always be mutliplying by a unitless scalar!

```
@foo: 0 20px 1.5em 20px;
body { margin: @foo * 2; }

# => body { margin: 0 40px 3em 40px; }
```

Multiplication by units wouldn't make sense unless LESS knows about the computed em size in the DOM and can make the proper conversion from px -> em -> px. (magic?)

However, multiplication by numbers alone should work as above, IMO. v1.1.12 suffers the existence of mixed declarations, but doesn't add this functionality. 

---

Actually, trying it just now, it doesn't much like operating on homogenous compound declarations either:

```
@foo: 20px 20px;
body { margin: @foo * 2; }
```

results in this error (ruby1.9):

```
no .<digit> floating literal anymore; put 0 before dot (SyntaxError)
20.020.0*2.0
       ^
(eval):1: syntax error, unexpected tINTEGER
20.020.0*2.0
```

but _shrug_... I'm not that concerned about it really, so long as the parser reads compound declarations without throwing an error.
