### ISSUE TITLE
Issue with shorthand CSS looking like operations

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#6]
Ok, had an issue with shorthand CSS when with using negative values. So for example:

margin: -10px 0 10px 0;

That will move the item up 10 pixels by creating a negative margin on top, then add 10 pixel margin below it. I had some code similar to this that caused some problems -- will go back and double check what it was. I think the CSS output was wrong, not an actual error by the compiler. I solved it by separating it out of short hand, so... margin-top: -10px; , but obviously that needs fixing.

**Comment by cloudhead** [comment]
Ah, good find, I think the engine is trying to do an operation here, because of the '-'. I'll have to make it a bit smarter, like:

-10 10 is not an operation, but 10 - 10 is.

**Comment by cloudhead** [comment]
Ok so there are three options:
1. force users to have spaces after operators, so 10 *10 isn't an operation.
2. force users to have spaces only after -, so 10 -10 isn't an operation, but 10 *10 is.
3. check if the spacing is consistent, so `10 - 10` and `10-10` are operations, but not 
   `10 -10`.

**Comment by cloudhead** [comment]
went for 3.

**Comment by ghost** [comment]
Great

**Comment by ghost** [comment]
Would this work:

10 + - 10

or

10 + -10

?

**Comment by sxeraverx** [comment]
maybe surround arithmetic operations in expr(), or something similar?

**Comment by cloudhead** [comment]
This has been solved by using parens around operations:

`margin: (2 + 2) 4 4 4;`
