### ISSUE TITLE
Minus sign before a variable

### ISSUE THREAD

**Issue by unindented** [less/less.ruby#60]
Less chokes if I put a minus sign before a variable:
    margin-left: -@width;

Not a huge problem, I can work around it with:
    margin-left: @width \* -1;

Nevertheless, if it's an easy fix, it would be welcome.

**Comment by cloudhead** [comment]
Definitely something on the todo list : )

**Comment by LonTypLAB** [comment]
top: - @var; // minus space ampersand

is also a workaround, although I would prefer the fix
