### ISSUE TITLE
Error about mixed units?

### ISSUE THREAD

**Issue by onlinesid** [less/less.ruby#61]
! Error: `0.0 -40.0px 1.5em 40.0px` you're  mixing units together! What do you expect?

It doesn't give me information about the error line. Also I have not actually added any of LESS codes, this is just straight from blueprint 0.9 main.css. I copied it as main.less and compiled it and got that error.

I think it's this line that is causing the error:

.push-1 {margin:0 -40px 1.5em 40px;}

**Comment by guns** [comment]
See issue #59:

http://github.com/cloudhead/less/issues/#issue/59

**Comment by cloudhead** [comment]
closing this because of #59
