### ISSUE TITLE
BUG : less' to_proc breaks Rails migrations, .. (ex: multi-columns add_index)

### ISSUE THREAD

**Issue by alainravet** [less/less.ruby#64]
less breaks Rails' migrations like 
    add_index :user, [:group_id, :status_id] 
    # single column add_index works fine 

The problem happens in  the file lib/ext.rb, line 59 
, where Symbol.to_proc is defined slightly differently from Rails 

lessCss' implementation : 
    class Symbol 
      def to_proc 
        proc {|obj, *args| obj.send(self, *args) } 
      end 
    end 

Rails' implementation : 

```
unless :to_proc.respond_to?(:to_proc)
  class Symbol 
    def to_proc 
      Proc.new { |*args| args.shift.__send__(self, *args) } 
    end 
  end 
end 
```

**Comment by tooky** [comment]
This will also affect Ruby 1.9 compatibility which has Symbol#to_proc defined in core. I have added a simple patch here: http://github.com/tooky/less/commit/595b7530e0b275372afe640cab76c855d0a09312

**Comment by cloudhead** [comment]
Thanks, merged.
