### ISSUE TITLE
Error with data URLs.

### ISSUE THREAD

**Issue by mcvsama** [less/less.ruby#71]
Example:
background: url(data:image/png;base64,abc) repeat-x scroll 0 0;
compiles to
background: url(data:image/png;base64, abc) repeat-x scroll 0 0;

Workaround: put '' around URL content.

**Comment by crsantos** [comment]
Can you give an example?
Like:

background: url("data:image/png;base64,abc");
or
background: url(data:image/png;base64,"abc");
?

Doesn't work both ways :(

**Comment by mcvsama** [comment]
url("data:image/png;base64,abcdef") worked for me when I was filing this issue.

**Comment by mcvsama** [comment]
Or maybe try using single quotes?
