### ISSUE TITLE
Temp File Conflict?

### ISSUE THREAD

**Issue by semiapies** [less/less.ruby#73]
In the last few iterations of less, jEdit kept throwing a fit while trying to save a .less file at the same time that lessc was running under the --watch option.  (Running on WinXP.)  To get this to work, I had to disable two-stage saving in jEdit, which normally generates a temp file with the naming scheme #filename#save# in the same directory as the file.  jEdit kept complaining that it couldn't access that temp file.

If this was due to lessc generating a temp file with the same naming scheme, I'm not sure this qualifies as a _bug_, but it was a problem that threw me for a bit until I could find the work-around.

**Comment by cloudhead** [comment]
weird. lessc doesn't generate a temp file... it just rewrites the output file on every change.
