### ISSUE TITLE
Return non-zero exit value on error

### ISSUE THREAD

**Issue by znerd** [less/less.ruby#74]
When <tt>lessc</tt> exists, it currently (version 1.1.13) seems to always return exit code 0, even if syntax errors were encountered. I'd prefer that in case of any error, a non-zero exit value would be returned, so that failures can be detected easily by wrapper scripts, Ant/Maven tasks, etc.

That would also make the <tt>lessc</tt> script more UNIX-compliant.

Test case: have a file <tt>foo.less</tt> with the following contents:
    {
Run:
    $ lessc foo.less bar.css
    $ echo $?
on a UNIX/Linux system (excluding the dollar-sign, of course).

The current output from the second command is:
    0
if my suggestion would be implemented, it would returned a different value, e.g.:
    1

**Comment by cloudhead** [comment]
You're right, I'll fix this.

**Comment by cloudhead** [comment]
fixed in 1.2.4
