### ISSUE TITLE
Send error output to stderr (instead of stdout)

### ISSUE THREAD

**Issue by znerd** [less/less.ruby#75]
Currently, lessc seems to send all error output to stdout. It would be more UNIX-compliant and more convenient for developers of wrapper scripts and/or Ant/Maven tasks if lessc would send the error messages to stderr instead.

Test case: Have a file foo.less with the following contents:
    {
then run (on a UNIX or Linux system):
    $ lessc foo.less 2>err.out >out.out
Expected result is that the output is in err.out, but in fact it is in out.out.

What _does_ work well is that when a file is not found, the error is actually sent to stderr.

**Comment by cloudhead** [comment]
Good call, I was pretty sloppy with the stderr/stdout stuff.

**Comment by cloudhead** [comment]
fixed in 1.2.3
