### ISSUE TITLE
Special terminal instructions only if terminal supports them

### ISSUE THREAD

**Issue by znerd** [less/less.ruby#76]
When the output device does not support special terminal instructions (typically colors), please suppress them.

For example, running:
    lessc a.less > out

should not produce special instructions.

**Comment by cloudhead** [comment]
Yea, this is something I'm aware of, as the Windows shell doesn't support these either. I'll have to figure out how to check.

**Comment by cloudhead** [comment]
I just pushed a fix to this (1.2.12) — it checks for $stdout.tty? — but you can still overwrite it with `--color`.
