### ISSUE TITLE
:nth-last-child(2) doesn't work

### ISSUE THREAD

**Issue by sandstrom** [less/less.ruby#77]
// ERROR
! Syntax Error: on line 507: expected one of :: : \* . # - [ @media @font-face got 2 after:

ol.comma > li:nth-last-child(

// CODE
    ol.comma > li:nth-last-child(2)::after,
    ul.comma > li:nth-last-child(2)::after {
        /\* no comma on second last… */
        content:"&";
    }

// REFERENCE
http://www.w3.org/TR/css3-selectors/#nth-child-pseudo

**Comment by cloudhead** [comment]
thanks, will fix shortly. If you're using a lot of css3 stuff, it might be useful for me to use your stylesheet in my spec, if you don't mind!

**Comment by cloudhead** [comment]
fixed in 1.2.4
