### ISSUE TITLE
No support for data URIs

### ISSUE THREAD

**Issue by sandstrom** [less/less.ruby#78]
// ERROR

! Syntax Error: on line 1683: expected one of ) : got , after:

div.instruction::after {

  background-image:url(data:image/gif;base64

// CODE

background-image:url(data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAB0AAAAMCAYAAACeGbYxAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAJRJREFUeNpi/P//PwMMfNzaAebweXsyUAt82rodTPN7VzDCxJiQFcAkYAppYSGGpdS0GJeFWC2lhsX4LMSwFBinFFuMzUJkc7H6lBKLibEQZ/D+Z7hIssWEgpSgpaRajM1CkH5kM4iylFiLcVlIlk+JsZgcC0GAEa1EwqkQaDBGyUVMosGmn4nYrIAtVRNrIToACDAAFNdtvUcGQCoAAAAASUVORK5CYII=);

**Comment by sandstrom** [comment]
http://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by cloudhead** [comment]
Duplicate of #71
