### ISSUE TITLE
less extensions should behave as css, should overwrite previous properties

### ISSUE THREAD

**Issue by sandstrom** [less/less.ruby#80]
@headingColor: blue;
@headingColor: red;

h1 {
color: @headingColor;
}

Text should be red, will be blue. Perhaps it would be better if the less extensions behaves like css would, eg. that the color is blue.

**Comment by cloudhead** [comment]
I decided to make variables immutable. They're more like constants really. Because Less isn't a programming language, redefining variables doesn't really make sense.

**Comment by sandstrom** [comment]
sounds reasonable, I withdraw my suggestion ;)
