### ISSUE TITLE
Wrong output when a parsing selector containing an attribute selector followed by a class selector

### ISSUE THREAD

**Issue by mechanicalchopsticks** [less/less.ruby#84]
When a selector contains an attribute selector followed by a class selector less insert a descendant selector combinator between them, for example:
    input[type="text"].required {}
becomes:
    input[type="text'] .required {}

**Comment by cloudhead** [comment]
support for more complex chained selectors such as input[attr=1].class#id:not().. Closed by f3042c176329712d10fd1eecf25936f69ed50530 -- removed class_id rule
