### ISSUE TITLE
Timestamp on watch output

### ISSUE THREAD

**Issue by sandstrom** [less/less.ruby#86]
Timestamp on watch output would make it easier to see the updates when the buffer is full. 

Otherwise it's just another ": Change detected... \* Updated file.css" among the other, so it's impossible to know that the buffer has updated.

**Comment by cloudhead** [comment]
good idea!

**Comment by j0hnsmith** [comment]
Great idea, you beat me to it.

**Comment by cloudhead** [comment]
Implemented this in 1.2.14:

```
lessc file.lss -wt
```

or

```
lessc file.lss -w --timestamps
```
