### ISSUE TITLE
Nested code in mixin with arguments

### ISSUE THREAD

**Issue by pixel2** [less/less.ruby#87]
When using a nested arguments inside the new @mixins the compiler crashes. I tried to convert my normal mixins to mixins with variables with the purpose to hide some of them from exporting. But the following mixin crashes the compiler when i try to call the mixin later in the code.

<pre>@clearfix() {
    zoom: 1;
    
    :after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden; 
    }
}

body { @clearfix(); }
</pre>

output:

<pre>.../element.rb:125:in `mix': undefined method`copy' for #Less::Node::Element:0x1d812f0 (NoMethodError)
[...]</p>

**Comment by cloudhead** [comment]
Is this with 1.2.7?

**Comment by pixel2** [comment]
That is true, version 1.2.7 (I got it eventually ;))

**Comment by cloudhead** [comment]
That code should work now, closing this issue. See issue 104 for more info on the dynamic mixins.
