### ISSUE TITLE
! Name Error - no line number

### ISSUE THREAD

**Issue by j0hnsmith** [less/less.ruby#88]
I missed the colon after a property

```
height 156px;
```

and got this error

: Change detected... ! Name Error: *\* is undefined.

It would be nice if the error message quoted the line number of the error.

I'm using 1.1.13

**Comment by sgabello** [comment]
I switched from 0.8.x to 1.1.13 and having the same undefined error.
Unfortunately the .less file is 1500 rows long and I have no idea on how to find where is the error.

Please... we need at least the line number!!! :D

Thanks

**Comment by rk** [comment]
Sadly, this error can also be caused by ID selectors ([see my issue here](http://github.com/cloudhead/less/issues/#issue/92)).

**Comment by cloudhead** [comment]
looking into this!

**Comment by cloudhead** [comment]
I improved the error reporting over the last couple of versions (1.2.10+), closing this for now, if you get another similar error, please report!
