### ISSUE TITLE
nesting :hover type selectors

### ISSUE THREAD

**Issue by cloudhead** [less/less.ruby#9]
Currently, this won't work as expected:
    .milk {
        :hover { color: white; }
        :focus { color: cream; }
    }

**Comment by ghost** [comment]
I think that's fine. 

When you nest something, it implies inheritance. .milk:hover isn't an inherited item under .milk, it's a pseudo-class of milk, so it's really a separate item. I think it's fine to write out .milk:hover in full as a separate selector. 

The only thing the above idea would do is make it more convenient to organize all related pseudo classes, but this organization comes at a cost of ambiguity because as I mentioned about :hover isn't inheritance.

**Comment by cloudhead** [comment]
Well, in a way, it's a pseudo class, with .milk as its parent class. Maybe I'll move it to 1.2, it makes sense to allow this, keeps the code dry.

**Comment by timothyjoh** [comment]
it does make sense to keep the source clean this way. I would like to see this implemented

**Comment by ghost** [comment]
.milk:hover elements are a subset of .milk elements - in that sense, I think this syntax makes a lot of sense.

+1, as they say :)

**Comment by lepot311** [comment]
If the point of less is to make css easier, faster, and cleaner to write, then this is a step in that direction.

**Comment by ghost** [comment]
Ok, as you know, I changed my mind on this issue :) Looking forward to this in 1.0

**Comment by mcvsama** [comment]
I would read this syntax as .milk :hover / .milk :focus. That is :hover for ANY element that is INSIDE .milk. Implementing .milk:hover as .milk { :hover } would be not logical. It's the same way .a { .b } is .a .b and NOT .a.b. I think there should be another syntax for this to avoid inconsistency, maybe .a { &:hover } saying that inner :hover is for parent selector? Also .a { &.b } would mean .a.b.

**Comment by cloudhead** [comment]
interesting, I'll think about this. I think most people use pseudo classes like `a:hover`, and not `a :hover`, so this is more convenient. It would indeed be more consistent if it behaved the other way though.

**Comment by ghost** [comment]
cloudhead: that's because "a :hover" won't work. Hover is a state of a, now a nested element, so it has to be written without spaces. Same thing as targeting an anchor with a specific id or class, where you'd go: "a#id" or "a.class"

**Comment by cloudhead** [comment]
but doesn't `a :hover` target the `hover` action of all of `a`'s children?

**Comment by mcvsama** [comment]
Yes, it does. Maybe `:hover` on all subelements is rarely used, better example would be `form :focus { color: blue }`.
