### ISSUE TITLE
Ending ID selector and multiple ID selectors cause syntax errors.

### ISSUE THREAD

**Issue by rk** [less/less.ruby#92]
The following is the error I get:

```
: Change detected...
! Name Error: * is undefined.
* Press [return] to continue...
```

As you can see, this was incredibly ambiguous and took nearly 45 minutes to track down. It truly needs to be improved. The code in question is:

```
p, blockquote, #navigation {
  letter-spacing: 1px;
  word-spacing: 2px;
}
```

To solve this syntax error one of a few things can be done:
1. Place ID selectors first.
2. Don't include an ID selector at the end of the list.
3. Prefix the ID selector with an element type (`ul#navigation`)
4. Don't do that. ;-)

But, multiple selectors cause such errors too! Here are a few more failure examples:

```
#navigation, img#logo, div#page { color: fuschia; }
#navigation, #logo, div#page { color: fuschia; }
#navigation, #logo, #page { color: fuschia; }
#navigation, img#logo, #page { color: fuschia; }
#navigation, img#logo, div#page { color: fuschia; }
```

As you can see, multiple ID selectors seems to cause problems when the first selector doesn't contain an element-prefix.

**Comment by cloudhead** [comment]
I can't seem to reproduce your errors.. works fine on 1.1.13 and 1.2.8 here

**Comment by rk** [comment]
That's bizarre. Let me attempt to put together a flawed sheet and post the whole source code here.

**Comment by cloudhead** [comment]
Closing this, feel free to reopen if you re-encounter the issue.
