### ISSUE TITLE
Faking Mixin Arguments

### ISSUE THREAD

**Issue by daz-codes** [less/less.ruby#93]
leafo left this comment in issue 16:

"this is already possible due to the delayed evaluation

@arg: red;
.function { color: @arg; }

body { @arg: blue; .function; }
a { @arg: green; .function; }
p { .function; }

The results are what you expect

a { color: green; }
body { color: blue; }
p { color: red; }"

I don't get this output. All of the colours are red for me. Should it work? This would be a good way to fake arguments for mixins until that functionality arrives.

DAZ

**Comment by rk** [comment]
See the section titled "scope" from the Less CSS documentation at [lesscss.org/docs.html](http://lesscss.org/docs.html). It would appear to be that scope has eclipsed what you used to be able to do; at least mixins will soon have arguments.

> Scope in LESS is very similar to that of programming languages. Variables and mixins are first looked for locally, and if they aren't found, the compiler will look in the parent scope, and so on. Note that the order of declaration does matter.

**Comment by daz-codes** [comment]
The way I read the section on scope was to mean the code example _would_ work.

Surely in the body declaration the colour:blue; variable should be interpreted first as it is in scope for the body declaration? But everything is coming out as red....

**Comment by xdissent** [comment]
The passage above about scope is valid. You're expecting the mixin to be reevaluated, which I don't believe happens. What version of LESS are you running? You can use the following in LESS 1.2.8 to achieve the desired results:

```
.function(@arg: red){
    color: @arg;
}

a {
    @arg: green;
    .function(@arg);
}

body {
    @arg: blue;
    .function(@arg);
}

p {
    .function;
}
```

which outputs:

```
a { color: green; }
body { color: blue; }
p { color: red; }
```

One issue I currently have is that LESS doesn't accept color names as arguments, which is why I'm creating a local `@arg` in the `a` and `body` declarations. If you were using hex colors (or anything else) you could call `.function(#0f0);` directly.

**Comment by xdissent** [comment]
Well it appears you actually can't pass any non-special argument to a mixin in 1.2.8. This was working in 1.2.7. This is fine:

```
.function(@arg: 3) {
    width: @arg;
}

body {
    .function(2px);
}
```

but this breaks:

```
body {
    .function(2);
}
```

I'll be posting a new issue shortly.

**Comment by xdissent** [comment]
Except of course that the `.function` mixin should be declared and called as `@function` in 1.2.7! Oops

**Comment by daz-codes** [comment]
I definitely want the functionality (arguments for mixins) that you're describing.
I'm running version 1.1.13 that I installed from the gem. How can I install the 1.2 version?

**Comment by xdissent** [comment]
You're in luck. Sort of. For now, run these commands:

```
sudo gem sources -a http://gems.github.com # if you haven't done this already
sudo gem install cloudhead-less
```

That should get you 1.2.8. Unfortunately, GitHub just discontinued they're gem building and hosting service (WTF? right?) so in the future you might have to build your own gem.

**Comment by cloudhead** [comment]
I'm gonna be hosting a gemcutter version soon, for the dev builds

**Comment by cloudhead** [comment]
1.2.9 is out, and on gemcutter. see the welcome message on the google groups page.

**Comment by cloudhead** [comment]
Closing, as 1.2.\* is now widely available (on gemcutter)
