### ISSUE TITLE
Variables in shorthand notation

### ISSUE THREAD

**Issue by daz-codes** [less/less.ruby#95]
@gap:10px;
.col{
margin:@gap/2 0 @gap/2 @gap;padding:0;
}

I was expecting this to return
.col{margin:5px 0 5px 10px;padding:0;}

But I get this error
! Syntax Error: on line 3: expected one of ; } got 0 after:

Is it not possible to use variables with shorthand notation?

DAZ

**Comment by cloudhead** [comment]
it certainly is possible, but if you want to do operations on them, you have to use parens:

```
@gap:10px; 
.col { margin: (@gap/2) 0 (@gap/2) @gap; padding: 0; }
```
