### ISSUE TITLE
Arguments without units

### ISSUE THREAD

**Issue by daz-codes** [less/less.ruby#96]
I'm trying out v1.2.8 from github and am trying to do this:
.gap(@factor:1){margin-left:10px \* factor}

.class{.gap(@factor:2)}

But LESS complains because @factor has no units (The error message is that \* is not defined).

But in this case it is a scale factor and the units are defined in the actual margin-left property. Is it possible to allow arguments that don't have units in time for 1.2 final?

DAZ

**Comment by cloudhead** [comment]
the problem here is the way you're calling .gap, this is the right way:

```
.class { .gap(2); }
```

**Comment by daz-codes** [comment]
Hi Cloudhead, thanks for the response.

That is what I was expecting, but it definitely doesn't work for me. I have to write
` .class { .gap(2px); }
to make it work - and the units have to be consistent.

cheers,

DAZ

**Comment by xdissent** [comment]
Yeah this is the bug I mentioned briefly in the other issue last night. It's definitely broken now, but seemed to be working without units in 1.2.7. That's very strange because the changelog shows very little difference between the two. Also, it appears that you CAN use arguments without units, but only if they are followed by another argument.

This works:

```
.test(@arg1: 10, @arg2: #f00) {
    padding: @arg1 * 2px;
    color: @arg2;
}

body {
    .test(15, #0f0);
}
```

This breaks:

```
.test(@arg1: 10, @arg2: #f00) {
    padding: @arg1 * 2px;
    color: @arg2;
}

body {
    .test(15);
}
```

**Comment by cloudhead** [comment]
ok that's quite weird, I'll check it out. I'm currently rewriting the mixin code completely, because it's not very solid.

**Comment by xdissent** [comment]
Well, it looks like adding a space after the argument allows you to pass a number without units, so it should be a pretty simple fix. I discovered this working on Grid LESS, which you should check out! =)
http://xdissent.github.com/grid-less

**Comment by cloudhead** [comment]
this should work in the freshly pushed 1.2.9 — can you confirm?

you can get the gem from gemcutter: `gem install less -s http://gemcutter.org`

**Comment by daz-codes** [comment]
At the moment I'm just getting this horrible error message!

/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/less-1.2.9/bin/../lib/less/engine/nodes/element.rb:157: syntax error, unexpected '\n' (SyntaxError)
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`polyglot_original_require'
    from /usr/lib/ruby/gems/1.8/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /usr/lib/ruby/gems/1.8/gems/less-1.2.9/bin/../lib/less/engine/nodes.rb:6
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
    from /usr/lib/ruby/gems/1.8/gems/polyglot-0.2.9/lib/polyglot.rb:70:in`require'
    from /usr/lib/ruby/gems/1.8/gems/less-1.2.9/bin/../lib/less/engine.rb:3
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`polyglot_original_require'
    from /usr/lib/ruby/gems/1.8/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require'
    from /usr/lib/ruby/gems/1.8/gems/less-1.2.9/bin/../lib/less.rb:14
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/less-1.2.9/bin/lessc:7
    from /usr/bin/lessc:19:in`load'
    from /usr/bin/lessc:19

**Comment by cloudhead** [comment]
sorry bout that, forgot to test in ruby 1.8 : ) — should work now (1.2.10)

**Comment by daz-codes** [comment]
Yes working now - no units needed in arguments.

Should I upgrade to Ruby 1.9?

DAZ

**Comment by cloudhead** [comment]
if you don't have any ties to 1.8, yes : ) — it runs faster.
